version: "3"
services:
  app:
    image: yt8492/reiwa-fake-news-backend:latest
    container_name: "reiwa-fake-news-backend"
    ports:
      - "8080:8080"
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://db:5432/reiwa-fake-news-db
      DB_USER: zli
      DB_PASSWORD: osg7w8r93oeis
    depends_on:
      - db

  db:
    image: postgres:10.1-alpine
    container_name: "reiwa-fake-news-db"
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: reiwa-fake-news-db
      POSTGRES_USER: zli
      POSTGRES_PASSWORD: osg7w8r93oeis

volumes:
  db-data:
    driver: local